Repository OpenMined/openmined, pull requests merged in 2021-03, with the labels that each got.

#133 feat: adds Simulcast support to courses 1.0
  apps/courses/src/components/CourseCard.tsx
  apps/courses/src/components/CourseProgressCard.tsx
  apps/courses/src/components/NumberedAccordion.tsx
  apps/courses/src/routes/courses/_helpers.ts
  apps/courses/src/routes/courses/lesson-complete/index.tsx
  apps/courses/src/routes/courses/overview/index.tsx
  apps/firebase-api/src/app/sanity/utils/queries.ts
  apps/sanity-api/src/schemas/course.ts
Labels: Status: Completed :heavy_check_mark:, Type: New Feature :heavy_plus_sign:

#141 fix: Mentor dashboard Simulcast crash
  apps/courses/src/routes/users/dashboard/Mentor.tsx
Labels: Type: Bug :bug:

#134 Ensure Mentors completion displays 100% in the Dashboard
  apps/courses/src/components/CourseProgressCard.tsx
  apps/courses/src/routes/courses/_helpers.ts
  apps/courses/src/routes/courses/overview/index.tsx
  apps/courses/src/routes/users/dashboard/Student.tsx
  apps/courses/src/routes/users/dashboard/index.tsx
Labels: Type: Improvement :chart_with_upwards_trend:
